<a href="https://colab.research.google.com/github/LailaBulh/Programacion---Claas-Files/blob/main/FactorizacionMatrices_LB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import lu, cholesky, qr, svd

In [28]:
### Declaracion de matriz A

A = np.array([[3, 3, 9],
             [18, 9, 3],
             [1, 6, 3]], dtype= float)

### Declaracion de matriz B

B = np.array([[18, 9 ,3],
             [1, 6, 3],
             [3, 3, 9]], dtype= float)

print('Matriz A:\n', A)

print('Matriz B diagonalmente predominante: \n', B)

Matriz A:
 [[ 3.  3.  9.]
 [18.  9.  3.]
 [ 1.  6.  3.]]
Matriz B diagonalmente predominante: 
 [[18.  9.  3.]
 [ 1.  6.  3.]
 [ 3.  3.  9.]]


# Obtenga la factorización LU de la matriz B




In [18]:
P, L, U = lu(B)

print('Matriz L:\n', L)

print('\nMatriz U:\n', U)

print('\nReconstruccion: \n', P @ L @ U)

print('\nMatriz P:\n', P)


Matriz L:
 [[1.         0.         0.        ]
 [0.05555556 1.         0.        ]
 [0.16666667 0.27272727 1.        ]]

Matriz U:
 [[18.          9.          3.        ]
 [ 0.          5.5         2.83333333]
 [ 0.          0.          7.72727273]]

Reconstruccion: 
 [[18.  9.  3.]
 [ 1.  6.  3.]
 [ 3.  3.  9.]]

Matriz P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
P, L, U = lu(A)

print('Matriz L:\n', L)

print('\nMatriz U:\n', U)

print('\nReconstruccion: \n', P @ L @ U)

print('\nMatriz P:\n', P)



Matriz L:
 [[ 1.          0.          0.        ]
 [-0.05555556  1.          0.        ]
 [-0.16666667 -0.23076923  1.        ]]

Matriz U:
 [[18.          9.         -3.        ]
 [ 0.          6.5        -3.16666667]
 [ 0.          0.          7.76923077]]

Reconstruccion: 
 [[-3. -3.  9.]
 [18.  9. -3.]
 [-1.  6. -3.]]

Matriz P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


# Obtenga la factorización QR de la matriz B

In [27]:
Q, R = qr(B)

print('Matriz Q:\n', Q)

print('Matriz R:\n', R)

print('\nReconstruccion: \n', Q @ R)

Matriz Q:
 [[-0.98491618  0.09497167 -0.14463921]
 [-0.05471757 -0.96396243 -0.26035058]
 [-0.1641527  -0.2485092   0.95461881]]
Matriz R:
 [[-18.27566688  -9.6850091   -4.5962755 ]
 [  0.          -5.67455715  -4.84355505]
 [  0.           0.           7.37659989]]

Reconstruccion: 
 [[18.  9.  3.]
 [ 1.  6.  3.]
 [ 3.  3.  9.]]


#Obtenga la factorización en valores singulares de la matriz B


In [23]:
U, s, Vt = svd(B, full_matrices=False)

print('Matriz U:\n', U)

print('\nMatriz s:\n', s)

print('\nMatriz Vt:\n', Vt)

print('\nReconstruccion: \n', U @ np.diag(s) @ Vt)

Matriz U:
 [[-0.92978188  0.36266682  0.06307483]
 [-0.21290979 -0.3900395  -0.89584519]
 [-0.30029165 -0.84636988  0.43986697]]

Matriz s:
 [21.62010328  8.65116007  4.09005665]

Matriz Vt:
 [[-0.82561394 -0.4878039  -0.28356478]
 [ 0.41599665 -0.18672007 -0.88999011]
 [ 0.38119341 -0.85275024  0.35708348]]

Reconstruccion: 
 [[18.  9.  3.]
 [ 1.  6.  3.]
 [ 3.  3.  9.]]
