<a href="https://colab.research.google.com/github/LailaBulh/Programacion---Claas-Files/blob/main/practica4_263166.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practica #4. Manipulación de matrices

link a github:

Manipulación de matrices

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

Suma ambas matrices.
Resta la segunda matriz de la primera.
Multiplica la primera matriz por 2.
Realiza una multiplicación matricial entre las dos matrices.

In [2]:
import numpy as np

In [20]:
### Definicion de matrices

m1 = np.random.randint(1,11, (3,3))
m2 = np.random.randint(1,11, (3,3))

print(f'Matriz A: \n{m1}')
print(f'Matriz B: \n{m2}')

### Suma de matrices
sum = m1 + m2
print(f'La suma de las matrices A y B es: \n{sum}')

### Resta de matrices
subs = m1 - m2
print(f'La resta de la matrices B menos A es: \n{subs}')

### Matriz A por 2
doub = np.dot(m1,2)
print(f'La matrices A multiplicada por 2 es: \n{doub}')

### Multiplicacion de matrices
mult = np.dot(m1,m2)
print(f'La multiplicacion de la matriz A * B es: \n{mult}')

Matriz A: 
[[ 6  2  9]
 [ 9  6  5]
 [ 6  4 10]]
Matriz B: 
[[ 6  7  2]
 [ 6  7 10]
 [ 5  8  1]]
La suma de las matrices A y B es: 
[[12  9 11]
 [15 13 15]
 [11 12 11]]
La resta de la matrices B menos A es: 
[[ 0 -5  7]
 [ 3 -1 -5]
 [ 1 -4  9]]
La matrices A multiplicada por 2 es: 
[[12  4 18]
 [18 12 10]
 [12  8 20]]
La multiplicacion de la matriz A * B es: 
[[ 93 128  41]
 [115 145  83]
 [110 150  62]]
